[data]
children = ["orig", "cache", "sigma"]

[data.orig]
children = ["sigma", "hmgcr"]

[data.orig.hmgcr]
children = ["csv", "xlsx"]

[data.orig.sigma]
children = ["csv", "xlsx"]

[data.cache]
children = ["csv", "dtw"]

[data.cache.dtw]
children = ["full", "subsample"]

[data.cache.dtw.subsample]
children = ["diff", "raw"]

[data.graph]
children = ["html", "png"]

[data.graph.png]
children = ["dtw"]
