[data_processing]
metadata = "data/orig/hmgcr/all_animal.csv"
batches = [
  "data/orig/hmgrc/xlsx/cohort1_2025_01_20_male.xlsx",
  "data/orig/hmgrc/xlsx/cohort1_2025_01_31_male.xlsx",
  "data/orig/hmgrc/xlsx/cohort2_2025-03-06_male.xlsx",
  "data/orig/hmgrc/xlsx/cohort2_2025_03_14_12_male.xlsx",
  "data/orig/hmgrc/xlsx/cohort3_2025_03_21_female.xlsx",
  "data/orig/hmgrc/xlsx/cohort4_2025_04_30_female.xlsx",
  "data/orig/hmgrc/xlsx/cohort5_2025_05_22_male.xlsx",
  "data/orig/hmgrc/xlsx/cohort5_2025-05-29_male.xlsx",
]
out_dir = "data/cache/hmgcr/csv"
